### ISSUE TITLE
刷出来的分数被和谐了

### ISSUE THREAD

**Issue by zhujunxi** [hyb1996/WechatJumping.js#10]
刷了1000多分，关闭微信再打开就不见了。刷少点几百分也被和谐了。好像只有几分的时候不会和谐。

[笑哭]

**Comment by hyb1996** [comment]
这是因为微信开始检测点击位置了。已经更新了V2版本可以解决这个问题。

**Comment by Winter-is-comming** [comment]
区域随机点击可以吗

**Comment by Gtanxingwen** [comment]
V2版本不好用，我没成功过，跳一次就挂了，第一版还可以用吧

**Comment by hyb1996** [comment]
@Gtanxingwen 要按照那个gif图片操作。比如悬浮窗位置等

**Comment by zhujunxi** [comment]
V2版本很好用，速度快，基本每次都是中心，刷分很快,不会和谐。 @hyb1996 赞一个！

**Comment by Gtanxingwen** [comment]
我试了，那个模拟棋子一直在左边，怎么调系数都会跳出去

**Comment by yangzhanlong** [comment]
floaty is not found  怎么弄

**Comment by ZhaoYitong** [comment]
20000+，已经被黑名单

**Comment by xxan** [comment]
哈哈哈  前几天刷了1000多 没事  昨天上头干上1W5 ，今天直接gg ，刷几百也不行了
