### ISSUE TITLE
报这个错误 floaty is not defined

### ISSUE THREAD

**Issue by gsons** [hyb1996/WechatJumping.js#14]
报这个错误 floaty is not defined

**Comment by yangzhanlong** [comment]
floaty is not found

**Comment by knoxhy** [comment]
floaty is not found

**Comment by hyb1996** [comment]
使用该版本软件才能运行：https://github.com/hyb1996/Auto.js/releases/download/3.0.0Alpha40/release-3.0.0.Alpha40.apk
