### ISSUE TITLE
检测不到无障碍已开启？

### ISSUE THREAD

**Issue by TRO-KG** [hyb1996/WechatJumping.js#18]
无论开启无障碍模式与否，点击运行都会再次打开授权界面，开启后再运行依然如此，点运行就会跳转

**Comment by TRO-KG** [comment]
机型：华为P10

**Comment by hyb1996** [comment]
尝试锁住后台避免被杀

**Comment by TRO-KG** [comment]
@hyb1996看了一下运行日志，说重启一下试试，重启后果然能用，万能的重启啊！:smile:
