### ISSUE TITLE
huawei_p9 系数不对

### ISSUE THREAD

**Issue by heywrcoding** [hyb1996/WechatJumping.js#2]
跳得有时准有时不准

**Comment by hyb1996** [comment]
可以把第36行的debug改成true，然后运行脚本，遇到跳得不准的情况时，到SD卡debug目录下查看记录截图，看是识别棋子和方块位置错误还是系数的问题

**Comment by walkJohnp** [comment]
我的华为也有点问题，也在调着看

**Comment by heywrcoding** [comment]
不是系数的问题，它有时跳的远，有时跳的近。感觉是不是画面还没停下来的时候就截图计算了？是不是可以sleep()一下？

**Comment by heywrcoding** [comment]
但是看你的代码已经sleep了，所以感觉有点迷😂

**Comment by xuanmiao-zero** [comment]
@hyb1996 荣耀V9也是时远时近,并没有找到debug目录

**Comment by xuanmiao-zero** [comment]
@hyb1996 改为true了,但是没有找到debug目录

**Comment by hyb1996** [comment]
更新了v1脚本，可以分别设置向左和向右的系数。
