### ISSUE TITLE
想请教sleep()方法是如何实现

### ISSUE THREAD

**Issue by pavilion2t** [hyb1996/WechatJumping.js#5]
看到源码里面写了sleep(2000)这样的语句，但是据我所知JS里面没有sleep()方法，想请教是如何实现的？我搜了相关资料 https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep  ，JS里面一般是用setTimeout()方法进行异步操作处理

**Comment by hyb1996** [comment]
虽然这是JavaScript，但并不是纯的JavaScript，他可以调用android的api，因此直接调用java.lang.Thread.sleep()函数。有关Auto.js的实现参见[Auto.js](https://github.com/hyb1996/Auto.js).

**Comment by pavilion2t** [comment]
太感谢了~我研究一下

**Comment by yybgo** [comment]
调用的java里的多线程apl
