### ISSUE TITLE
一加5T，如何调整系数？每次都是几分就结束了，系数是怎么计算的？

### ISSUE THREAD

**Issue by DoveBoy** [hyb1996/WechatJumping.js#8]

**Comment by hyb1996** [comment]
http://www.autojs.org/topic/540/%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%9A%84%E8%84%9A%E6%9C%AC%E7%9A%84%E5%8D%8E%E4%B8%BA%E6%88%96%E8%99%9A%E6%8B%9F%E6%8C%89%E9%94%AE%E6%88%96%E5%85%A8%E9%9D%A2%E5%B1%8F%E6%89%8B%E6%9C%BA%E8%BF%9B
