### ISSUE TITLE
1080p的全面屏希望能够适应

### ISSUE THREAD

**Issue by PhelanZ** [hyb1996/WechatJumping.js#9]
希望能适应1080p的全面屏，小白不懂怎么改算法

**Comment by hyb1996** [comment]
试试这个帖子里的脚本http://www.autojs.org/topic/269/ts%E5%BE%AE%E4%BF%A1%E8%B7%B3%E4%B8%80%E8%B7%B3%E9%80%9A%E7%94%A8%E7%89%88

**Comment by hyb1996** [comment]
http://www.autojs.org/topic/540/%E6%97%A0%E6%B3%95%E4%BD%BF%E7%94%A8%E7%9A%84%E8%84%9A%E6%9C%AC%E7%9A%84%E5%8D%8E%E4%B8%BA%E6%88%96%E8%99%9A%E6%8B%9F%E6%8C%89%E9%94%AE%E6%88%96%E5%85%A8%E9%9D%A2%E5%B1%8F%E6%89%8B%E6%9C%BA%E8%BF%9B
